config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :groups
  resource :user, only: %i[show new create destroy]
  resources :memberships, only: %i[index show new create destroy]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    root to: 'users#index'
    resources :users
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group

  enum role: { general: 0, owner: 1 }

  validates :user, presence: true
  validates :group, presence: true
  validates :user, uniqueness: { scope: :group }
  validates :role, inclusion: { in: Membership.roles.keys }

  before_destroy :require_owner_existance

  scope :ownership, -> { where(role: :owner) }

  def self.create_with_group!(user, group)
    ActiveRecord::Base.transaction do
      group.save!
      group.memberships.create!(user: user, role: :owner)
    end
  end

  private

  def require_owner_existance
    return if role != 'owner'

    errors.add(:owner, 'はグループ所有者なのでやめられません')
    throw :abort
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    authorize!
    @memberships = current_user.memberships.includes(:group).page(params[:page])
  end

  def show
    @membership = current_user.memberships.find(params[:id])
    @group = @membership.group
    @owner = @group.owner
    @members = @group.users.includes(:tasks).page(params[:page])

    authorize! @membership
  end

  def create
    membership = current_user.memberships.build(group_id: params[:membership][:group_id], role: :general)
    authorize! membership

    membership.save!
    flash[:notice] = t('memberships.create_success')
    redirect_to membership_path(membership.id)
  end

  def destroy
    membership = current_user.memberships.find(params[:id])
    authorize! membership

    membership.destroy!

    flash[:notice] = t('memberships.delete_success')
    redirect_to root_path
  end
end

app/views/memberships/index.html.haml
- content_for :navbar_items do
  %li.nav-item
    .nav-link= link_to t('groups.explore'), groups_path, class: 'btn btn-light'
  %li.nav-item
    .nav-link= link_to t('groups.new'), new_group_path, class: 'btn btn-light'

.container
  %h1.mt-5= t('memberships.index')
.container
  .row
    - @memberships.each do |ms|
      .col-sm-6.col-lg-4
        .card.mt-3
          .card-body
            %h5.card-title= ms.group.name
            .card-text.mb-3= ms.group.description
            = link_to t('show'), membership_path(ms), class: 'card-link'
.container.pagination.justify-content-center.mt-3
  = paginate @memberships

app/views/memberships/show.html.haml
.section.jumbotron
  .container
    %h1.display-4= @group.name
    %p= t('groups.orgin_summary', created_at: I18n.l(@group.created_at, format: :long), owner_name: @owner.name)
    %p.lead= @group.description
    - if loyalty(@membership, :memberships).destroy?
      = form_with model: @membership, method: :delete, local: true do |f|
        = f.hidden_field :user_id
        = f.hidden_field :group_id
        = f.hidden_field :role
        = f.submit t('memberships.destroy'), class: 'btn btn-secondary'
    - if loyalty(@group, :groups).destroy?
      = form_with model: @group, method: :delete, local: true do |f|
        = f.hidden_field :group_id
        = f.submit t('groups.destroy'), class: 'btn btn-secondary'

.section
  .container
    %h2= t('groups.members')
    %p= t('groups.members_description')
    .accordion#accordion
      - @members.each_with_index do |member, i|
        .card
          .card-header{ id: "heading-#{i}" }
            %h5.mb-0
              %button.btn.btn-link.collapsed{ 'aria-controls' => "collapse-#{i}", 'aria-expanded' => 'true', 'data-target' => "#collapse-#{i}", 'data-toggle' => 'collapse', type: 'button' }
                = member.name
          .collapse{ id: "collapse-#{i}", 'aria-labelledby' => "heading-#{i}", 'data-parent' => '#accordion' }
            %ul.list-group.list-group-flush
              - member.tasks.each do |task|
                %li.list-group-item
                  %h5.mb-1= task.name
.container.pagination.justify-content-center.mt-3
  = paginate @members