config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :groups
  resource :user, only: %i[show new create destroy]
  resources :memberships, only: %i[index show new create destroy]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    root to: 'users#index'
    resources :users
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :delete_all
  has_many :users, through: :memberships, source: :user, inverse_of: :groups

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, length: { maximum: 2000 }

  def owner
    memberships.ownership.first.user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    authorize!
    @groups = Group.all.page(params[:page])
  end

  def show
    @group = Group.find(params[:id])
    @owner = @group.owner
    @member_count = @group.users.count
    @membership = @group.memberships.find_by(user_id: current_user.id) || @group.memberships.build
    authorize! @group
  end

  def new
    authorize!
    @group = Group.new
  end

  def create
    authorize!
    @group = Group.new(group_params)
    render :new and return if @group.invalid?

    ms = Membership.create_with_group!(current_user, @group)
    redirect_to membership_path(ms)
  end

  def update
    @group = Group.find(params[:id])
    authorize! @group

    if @group.save
      flash[:notice] = t('groups.update_success')
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    authorize! @group

    @group.destroy!

    flash[:notice] = t('groups.delete_success')
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/views/groups/_form.html.haml
- if group.errors.any?
  %ul
    - group.errors.full_messages.each do |message|
      %li= message
= form_with model: group, local: true do |form|
  .form-group.row
    .col-sm-3= form.label :name, class: 'col-form-label'
    .col-sm-9= form.text_field :name, class: 'form-control', placeholder: t('groups.placeholder.name'), autofocus: true
  .form-group.row
    .col-sm-3= form.label :description, class: 'col-form-label'
    .col-sm-9= form.text_area :description, class: 'form-control', placeholder: t('groups.placeholder.description')
  .form-group.row
    .col-sm-3
    .col-sm-9= form.submit t('create'), class: 'btn btn-primary btn-block'

app/views/groups/edit.html.haml
.container
  %h1.mt-5 t('groups.edit')
  = render partial: 'form', locals: { group: @group }
  = link_to t('back'), groups_path

app/views/groups/index.html.haml
- content_for :navbar_items do
  %li.nav-item
    .nav-link= link_to t('groups.new'), new_group_path, class: 'btn btn-light'
.container
  %h1.mt-5= t('groups.index')
.container
  .row
    - @groups.each do |g|
      .col-sm-6.col-lg-4
        .card.mt-3
          .card-body
            %h5.card-title= link_to g.name, group_path(g)
            .card-text.mb-3= g.description
.container.pagination.justify-content-center.mt-3
  = paginate @groups

app/views/groups/new.html.haml
.container
  %h1.mt-5= t('groups.new')
  = render partial: 'form', locals: { group: @group }
  = link_to t('back'), groups_path

app/views/groups/show.html.haml
.section.jumbotron
  .container
    %h1.display-4= @group.name
    %p= t('groups.orgin_summary', created_at: I18n.l(@group.created_at, format: :long), owner_name: @owner.name)
    %p.lead= @group.description
    - if @membership.new_record?
      = form_with model: @membership, local: true do |f|
        = f.hidden_field :user_id
        = f.hidden_field :group_id
        = f.hidden_field :role
        = f.submit t('memberships.create'), class: 'btn btn-secondary'
    - else
      - if loyalty(@membership, :memberships).destroy?
        = form_with model: @membership, method: :delete, local: true do |form|
          = form.hidden_field :user_id
          = form.hidden_field :group_id
          = form.hidden_field :role
          = form.submit t('memberships.destroy'), class: 'btn btn-secondary'
      - if loyalty(@group, :groups).destroy?
        = form_with model: @group, method: :delete, local: true do |form|
          = form.hidden_field :group_id
          = form.submit t('groups.destroy'), class: 'btn btn-secondary'