config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :groups
  resource :user, only: %i[show new create destroy]
  resources :memberships, only: %i[index show new create destroy]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    root to: 'users#index'
    resources :users
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title IncrementalTodo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light{ class: request.path.start_with?('/admin') ? 'bg-dark' : 'bg-light' }
      = link_to 'IncrementalTODO', root_path, class: 'navbar-brand text-secondary h1'
      %button.navbar-toggler{ 'aria-controls' => 'navbar-nav-dropdown', 'aria-expanded' => 'false', 'aria-label' => 'Toggle navigation', 'data-target' => '#navbar-nav-dropdown', 'data-toggle' => 'collapse', :type => 'button' }
        %span.navbar-toggler-icon
      .collapse.navbar-collapse.justify-content-end.mr-auto#navbar-nav-dropdown
        %ul.navbar-nav
          = yield :navbar_items
          - if logged_in?
            - if current_user.alarming_tasks.present?
              %li.nav-item.dropdown
                .nav-link.dropdown-toggle#navbar-dropdown-link-menu{ 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :href => '#' }
                  .btn.btn-warning= t('task_alarms.name')
                .dropdown-menu.dropdown-menu-right{ 'aria-labelledby' => 'navbar-dropdown-link-menu' }
                  %h5.dropdown-header= t('task_alarms.listing_message')
                  .dropdown-divider
                  - current_user.alarming_tasks.each do |k, v|
                    .dropdown-item= link_to v, task_path(k)
            %li.nav-item
              .nav-link= link_to current_user.name, user_path, class: 'btn btn-outline-primary'
            %li.nav-item
              .nav-link= link_to t('groups.name'), memberships_path, class: 'btn btn-outline-primary'
            %li.nav-item
              .nav-link= link_to t('logout'), session_path(current_user.id), method: :delete, class: 'btn btn-outline-secondary'
          - else
            %li.nav-item
              .nav-link= link_to t('login'), new_session_path, class: 'nav-link'
            %li.nav-item
              .nav-link= link_to t('signup'), new_user_path, class: 'nav-link'

    - flash.each do |k, v|
      .alert.alert-info{ role: 'alert' }
        = content_tag(:div, v, class: k.to_s)
    = yield